name: Test

on:
  pull_request:
  push:
    branches: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Package Managers
        run: corepack enable

      - name: Install Project Dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Check
        run: yarn run check

      - name: Build
        run: yarn run build

      - name: Story build
        run: yarn run story:build
